In [129]:
import requests
import csv
from astropy.io import ascii
import numpy as np
import pandas as pd

link = "https://www.astro.keele.ac.uk/jkt/tepcat/allinfo-csv.csv"

with requests.Session() as s:
    download = s.get(link)

    decoded_content = download.content.decode('utf-8')

    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
        
dat = pd.DataFrame(my_list[1:], columns=my_list[0])

dat

,System,Type,RA(deg),Dec(deg),Vmag,Kmag,length,depth,T0(HJDorBJD),T0err,...,errdn,Teq,err,err,Lambda,err,err,Psi,err,err
0,55_Cnc_e,TEP,133.14921,28.33083,5.95,4.01,0.06433,0.039,2457178.81780,0.00007,...,0.53,2349,188,193,10,17,20,23,14,12
1,pi_Men_c,TEP,84.29121,-80.46911,5.67,4.24,0.1246,0.03,2458509.8068,0.0003,...,0.4,1170,2.8,4.3,-24.0,4.1,4.1,26.9,5.8,4.7
2,AD_3116,BD,130.66429,19.41442,18.73,13.50,0.068,14,2457178.817792,0.000080,...,-1,1669,244,258,-999,-999,-999,-999,-999,-999
3,AU_Mic_b,TEP,311.28971,-31.34089,8.63,4.53,0.145,0.3,2460149.9550,0.0012,...,0.12,556,8,9,-4.7,6.8,6.4,-999,-999,-999
4,AU_Mic_c,TEP,311.28971,-31.34089,8.63,4.53,0.155,0.2,2460133.8718,0.0085,...,0.88,428,8,8,68,32,49,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,Kepler-1642b,KTEP,297.21213,43.64369,14.37,12.07,0.1003,0.13,2454967.05300,0.11200,...,-1,895,-1,-1,-999,-999,-999,-999,-999,-999
3864,Kepler-1642c,KTEP,297.21213,43.64369,14.37,12.07,0.0890,0.11,2454968.28900,0.12600,...,-1,1095,-1,-1,-999,-999,-999,-999,-999,-999
3865,Kepler-1644b,KTEP,285.47504,48.03492,14.38,12.55,0.1980,0.04,2454966.96316,0.00600,...,-1,606,-1,-1,-999,-999,-999,-999,-999,-999
3866,Kepler-1645b,KTEP,297.47946,48.41856,14.64,12.90,0.2158,0.04,2454965.32600,0.34500,...,-1,754,-1,-1,-999,-999,-999,-999,-999,-999
3867,Kepler-1646b,KTEP,287.52638,42.91289,16.79,12.03,0.0340,0.23,2454968.43172,0.00200,...,-1,365,-1,-1,-999,-999,-999,-999,-999,-999

In [130]:
#Storing  'System' & 'Type' columns as separate list to be re-added later
System = dat['System'].values.tolist()
Type = dat['Type'].values.tolist()

#Rename all column headers to avoid duplicate 'err' names
new_tepcat_colnames = ['System', 'Type', 'RA(deg)', 'Dec(deg)', 'Vmag', 'Kmag', 'length', 'depth', 'T0(HJDorBJD)', 'T0err',
                       'Period(day)', 'Perioderr', 'Teff', 'Teff_errup', 'Teff_errdn', '[Fe/H]', '[Fe/H]_errup', '[Fe/H]_errdn',
                       'M_A', 'M_A_errup', 'M_A_errdn', 'R_A', 'R_A_errup', 'R_A_errdn', 'loggA', 'loggA_errup', 'loggA_errdn', 
                       'rho_A', 'rho_A_errup', 'rho_A_errdn', 'e', 'e_errup', 'e_errdn', 'a(AU)', 'a(AU)_errup', 'a(AU)_errdn',
                       'M_b', 'M_b_errup', 'M_b_errdn', 'R_b', 'R_b_errup', 'R_b_errdn', 'g_b', 'g_b_errup', 'g_b_errdn',
                       'rho_b', 'rho_b_errup', 'rho_b_errdn', 'Teq', 'Teq_errup', 'Teq_errdn', 'Lambda', 'Lambda_errup', 'Lambda_errdn',
                       'Psi', 'Psi_errup', 'Psi_errdn']

# print (len(new_tepcat_colnames))
new_dat = dat.set_axis(new_tepcat_colnames, axis=1)

#dat.insert(1, "System2", System)

In [131]:
#First drop the two string columns at the start
new_dat.drop('System', axis=1, inplace=True)
new_dat.drop('Type', axis=1, inplace=True)

In [132]:
new_dat

,RA(deg),Dec(deg),Vmag,Kmag,length,depth,T0(HJDorBJD),T0err,Period(day),Perioderr,...,rho_b_errdn,Teq,Teq_errup,Teq_errdn,Lambda,Lambda_errup,Lambda_errdn,Psi,Psi_errup,Psi_errdn
0,133.14921,28.33083,5.95,4.01,0.06433,0.039,2457178.81780,0.00007,0.73654604,0.00000016,...,0.53,2349,188,193,10,17,20,23,14,12
1,84.29121,-80.46911,5.67,4.24,0.1246,0.03,2458509.8068,0.0003,6.267852,0.000016,...,0.4,1170,2.8,4.3,-24.0,4.1,4.1,26.9,5.8,4.7
2,130.66429,19.41442,18.73,13.50,0.068,14,2457178.817792,0.000080,1.98279436,0.00000023,...,-1,1669,244,258,-999,-999,-999,-999,-999,-999
3,311.28971,-31.34089,8.63,4.53,0.145,0.3,2460149.9550,0.0012,8.46314280,0.0000049,...,0.12,556,8,9,-4.7,6.8,6.4,-999,-999,-999
4,311.28971,-31.34089,8.63,4.53,0.155,0.2,2460133.8718,0.0085,18.858827,0.000050,...,0.88,428,8,8,68,32,49,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,297.21213,43.64369,14.37,12.07,0.1003,0.13,2454967.05300,0.11200,12.2064304,0.0009936,...,-1,895,-1,-1,-999,-999,-999,-999,-999,-999
3864,297.21213,43.64369,14.37,12.07,0.0890,0.11,2454968.28900,0.12600,6.6513189,0.0006042,...,-1,1095,-1,-1,-999,-999,-999,-999,-999,-999
3865,285.47504,48.03492,14.38,12.55,0.1980,0.04,2454966.96316,0.00600,21.0907909,0.0001467,...,-1,606,-1,-1,-999,-999,-999,-999,-999,-999
3866,297.47946,48.41856,14.64,12.90,0.2158,0.04,2454965.32600,0.34500,16.1780300,0.0510000,...,-1,754,-1,-1,-999,-999,-999,-999,-999,-999
3867,287.52638,42.91289,16.79,12.03,0.0340,0.23,2454968.43172,0.00200,4.4855921,0.0000114,...,-1,365,-1,-1,-999,-999,-999,-999,-999,-999

In [133]:
# Convert data types of all columns to float
tot_col_no = len(new_dat.columns)

for col in new_dat.columns:
    new_dat[col] = pd.to_numeric(new_dat[col], errors='coerce')
    new_dat[col].replace(-1, np.nan, inplace=True)
    new_dat[col].replace(-999, np.nan, inplace=True)

/var/folders/7c/5ddclhwd2776fv8rg4r8tx7w0000gn/T/ipykernel_46228/1410430619.py:6: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dat[col].replace(-1, np.nan, inplace=True)
/var/folders/7c/5ddclhwd2776fv8rg4r8tx7w0000gn/T/ipykernel_46228/1410430619.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  new_dat[col].replace(-999, np.nan, inplace=True)

In [135]:
#Re-inserting 'System' & 'Type' columns back into the dataframe
new_dat.insert(0, "System", System)
new_dat.insert(1, "Type", Type)

In [136]:
new_dat

,System,Type,RA(deg),Dec(deg),Vmag,Kmag,length,depth,T0(HJDorBJD),T0err,...,rho_b_errdn,Teq,Teq_errup,Teq_errdn,Lambda,Lambda_errup,Lambda_errdn,Psi,Psi_errup,Psi_errdn
0,55_Cnc_e,TEP,133.14921,28.33083,5.95,4.01,0.06433,0.039,2.457179e+06,0.00007,...,0.53,2349.0,188.0,193.0,10.0,17.0,20.0,23.0,14.0,12.0
1,pi_Men_c,TEP,84.29121,-80.46911,5.67,4.24,0.12460,0.030,2.458510e+06,0.00030,...,0.40,1170.0,2.8,4.3,-24.0,4.1,4.1,26.9,5.8,4.7
2,AD_3116,BD,130.66429,19.41442,18.73,13.50,0.06800,14.000,2.457179e+06,0.00008,...,NaN,1669.0,244.0,258.0,NaN,NaN,NaN,NaN,NaN,NaN
3,AU_Mic_b,TEP,311.28971,-31.34089,8.63,4.53,0.14500,0.300,2.460150e+06,0.00120,...,0.12,556.0,8.0,9.0,-4.7,6.8,6.4,NaN,NaN,NaN
4,AU_Mic_c,TEP,311.28971,-31.34089,8.63,4.53,0.15500,0.200,2.460134e+06,0.00850,...,0.88,428.0,8.0,8.0,68.0,32.0,49.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,Kepler-1642b,KTEP,297.21213,43.64369,14.37,12.07,0.10030,0.130,2.454967e+06,0.11200,...,NaN,895.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3864,Kepler-1642c,KTEP,297.21213,43.64369,14.37,12.07,0.08900,0.110,2.454968e+06,0.12600,...,NaN,1095.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3865,Kepler-1644b,KTEP,285.47504,48.03492,14.38,12.55,0.19800,0.040,2.454967e+06,0.00600,...,NaN,606.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3866,Kepler-1645b,KTEP,297.47946,48.41856,14.64,12.90,0.21580,0.040,2.454965e+06,0.34500,...,NaN,754.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3867,Kepler-1646b,KTEP,287.52638,42.91289,16.79,12.03,0.03400,0.230,2.454968e+06,0.00200,...,NaN,365.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN