In [112]:
import requests
import csv
from astropy.io import ascii
import numpy as np
import pandas as pd

link = "https://www.astro.keele.ac.uk/jkt/tepcat/allinfo-ascii.txt"

txt = requests.get(link).text

lines = txt.splitlines()
# Strip the leading comment marker from the header line
lines[0] = lines[0].removeprefix("#").strip()

ascii_dat = ascii.read(
    lines,
    format="fixed_width",
    delimiter=" ",
    comment=None,
)

dat = ascii_dat.to_pandas()
# Strip leading and trailing hyphens from column names
dat.columns = dat.columns.str.strip("-")

dat

,System,Type,RA_deg,Dec_deg,V-mag,K-mag,Tlength,Tdepth,T0-HJDorBJD,Porb-day,...,rho1-rhosun,eccentricity,sep-AU,M2-Mjup,R2-Rjup,g2-ms2,rho2-rhoJup,Teq-K,ProjObliquity,TrueObliquity
0,55_Cnc,TE,133.149,1 28.330,5.0,4.0,0.064,3 0.0,9 2457178.81780 0.000,0.73654604 0.00000,...,1.00 0.11 0.,0.05 0.03 0,0.01544 0.00005 0.000,0.0243 0.0012 0.00,0.1692 0.0039 0.00,21.4 2.1 1,4.71 0.56 0.,2349 188 1,10 17,23 14
1,pi_Men,TE,84.291,1 -80.469,5.0,4.0,0.124,0.0,2458509.8068 0.000,6.267852 0.00001,...,0.7442 0.0009 0.00,0.066 0.086 0.,0.06876 0.00065 0.000,0.0114 0.0012 0.00,0.1914 0.0013 0.00,11.0 1.9 9,2.1 0.4 0,1170 2.8 4,-24.0 4.1 4,26.9 5.8 4
2,AD_311,BD,130.664,9 19.414,18.0,13.0,0.068,14,2457178.817792 0.000,1.98279436 0.00000,...,-1 -1,0.144 0.045 0.,-1 -1,54.6 6.8 6,0.95 0.07 0.,-1 -1,-1 -1,1669 244 2,-999 -999 -9,-999 -999 -9
3,AU_Mic,TE,311.289,1 -31.340,8.0,4.0,0.145,0.3,2460149.9550 0.001,8.46314280 0.00000,...,1.106 0.099 0.0,0.07 0.09 0,0.0694 0.0027 0.00,0.0283 0.0082 0.00,0.412 0.013 0.0,-1 -1,0.37 0.12 0.,556 8,-4.7 6.8 6,-999 -999 -9
4,AU_Mic,TE,311.289,1 -31.340,8.0,4.0,0.155,0.2,2460133.8718 0.008,18.858827 0.00005,...,1.106 0.099 0.0,0.18 0.08 0,0.1169 0.0047 0.00,0.0455 0.0102 0.01,0.246 0.023 0.0,-1 -1,2.94 0.86 0.,428 8,68 32,-999 -999 -9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,Kepler,KT,297.212,3 43.643,14.0,12.0,0.100,0.1,2454967.05300 0.112,12.2064304 0.00099,...,-1 -1,-1 -1,-1 -1,-1 -1,0.483 0.198 0.2,-1 -1,-1 -1,895 -1,-999 -999 -9,-999 -999 -9
3864,Kepler,KT,297.212,3 43.643,14.0,12.0,0.089,0.1,2454968.28900 0.126,6.6513189 0.00060,...,-1 -1,-1 -1,-1 -1,-1 -1,0.429 0.177 0.1,-1 -1,-1 -1,1095 -1,-999 -999 -9,-999 -999 -9
3865,Kepler,KT,285.475,4 48.034,14.0,12.0,0.198,0.0,2454966.96316 0.006,21.0907909 0.00014,...,-1 -1,-1 -1,-1 -1,-1 -1,0.168 0.043 0.0,-1 -1,-1 -1,606 -1,-999 -999 -9,-999 -999 -9
3866,Kepler,KT,297.479,6 48.418,14.0,12.0,0.215,0.0,2454965.32600 0.345,16.1780300 0.05100,...,-1 -1,-1 -1,-1 -1,-1 -1,0.201 0.062 0.0,-1 -1,-1 -1,754 -1,-999 -999 -9,-999 -999 -9
3867,Kepler,KT,287.526,8 42.912,16.0,12.0,0.034,0.2,2454968.43172 0.002,4.4855921 0.00001,...,-1 -1,-1 -1,-1 -1,-1 -1,0.085 0.014 0.0,-1 -1,-1 -1,365 -1,-999 -999 -9,-999 -999 -9

In [ ]:
link2 = "https://www.astro.keele.ac.uk/jkt/tepcat/allinfo-csv.csv"

with requests.Session() as s:
    download = s.get(link2)

    decoded_content = download.content.decode('utf-8')

    cr = csv.reader(decoded_content.splitlines(), delimiter=',')
    my_list = list(cr)
        
dat2 = pd.DataFrame(my_list[1:], columns=my_list[0])

,System,Type,RA(deg),Dec(deg),Vmag,Kmag,length,depth,T0(HJDorBJD),T0err,...,errdn,Teq,err,err,Lambda,err,err,Psi,err,err
0,55_Cnc_e,TEP,133.14921,28.33083,5.95,4.01,0.06433,0.039,2457178.81780,0.00007,...,0.53,2349,188,193,10,17,20,23,14,12
1,pi_Men_c,TEP,84.29121,-80.46911,5.67,4.24,0.1246,0.03,2458509.8068,0.0003,...,0.4,1170,2.8,4.3,-24.0,4.1,4.1,26.9,5.8,4.7
2,AD_3116,BD,130.66429,19.41442,18.73,13.50,0.068,14,2457178.817792,0.000080,...,-1,1669,244,258,-999,-999,-999,-999,-999,-999
3,AU_Mic_b,TEP,311.28971,-31.34089,8.63,4.53,0.145,0.3,2460149.9550,0.0012,...,0.12,556,8,9,-4.7,6.8,6.4,-999,-999,-999
4,AU_Mic_c,TEP,311.28971,-31.34089,8.63,4.53,0.155,0.2,2460133.8718,0.0085,...,0.88,428,8,8,68,32,49,-999,-999,-999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3863,Kepler-1642b,KTEP,297.21213,43.64369,14.37,12.07,0.1003,0.13,2454967.05300,0.11200,...,-1,895,-1,-1,-999,-999,-999,-999,-999,-999
3864,Kepler-1642c,KTEP,297.21213,43.64369,14.37,12.07,0.0890,0.11,2454968.28900,0.12600,...,-1,1095,-1,-1,-999,-999,-999,-999,-999,-999
3865,Kepler-1644b,KTEP,285.47504,48.03492,14.38,12.55,0.1980,0.04,2454966.96316,0.00600,...,-1,606,-1,-1,-999,-999,-999,-999,-999,-999
3866,Kepler-1645b,KTEP,297.47946,48.41856,14.64,12.90,0.2158,0.04,2454965.32600,0.34500,...,-1,754,-1,-1,-999,-999,-999,-999,-999,-999
3867,Kepler-1646b,KTEP,287.52638,42.91289,16.79,12.03,0.0340,0.23,2454968.43172,0.00200,...,-1,365,-1,-1,-999,-999,-999,-999,-999,-999

In [106]:
dat2_nan = dat2.values.replace(-1, np.nan, inplace=True)

dat2_nan

AttributeError: 'numpy.ndarray' object has no attribute 'replace'

In [108]:
# select the float columns
df_num = dat2.select_dtypes(include=[np.float])
# select non-numeric columns
df_num = dat2.select_dtypes(exclude=[np.number])

AttributeError: module 'numpy' has no attribute 'float'.
`np.float` was a deprecated alias for the builtin `float`. To avoid this error in existing code, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

In [97]:
# #Viewing the table in full
# with pd.option_context('display.max_rows', None,
#                        'display.max_columns', None,
#                        'display.precision', 3
#                        ):
#     display(dat2)

System          string[python]
Type            string[python]
RA(deg)         string[python]
Dec(deg)        string[python]
Vmag            string[python]
Kmag            string[python]
length          string[python]
depth           string[python]
T0(HJDorBJD)    string[python]
T0err           string[python]
Period(day)     string[python]
Perioderr       string[python]
Teff            string[python]
err             string[python]
err             string[python]
[Fe/H]          string[python]
erru            string[python]
errd            string[python]
M_A             string[python]
errup           string[python]
errdn           string[python]
R_A             string[python]
errup           string[python]
errdn           string[python]
loggA           string[python]
errup           string[python]
errdn           string[python]
rho_A           string[python]
errup           string[python]
errdn           string[python]
e               string[python]
errup           string[python]
errdown         string[python]
a(AU)           string[python]
errup           string[python]
errdown         string[python]
M_b             string[python]
errup           string[python]
errdn           string[python]
R_b             string[python]
errup           string[python]
errdn           string[python]
g_b             string[python]
errup           string[python]
errdn           string[python]
rho_b           string[python]
errup           string[python]
errdn           string[python]
Teq             string[python]
err             string[python]
err             string[python]
Lambda          string[python]
err             string[python]
err             string[python]
Psi             string[python]
err             string[python]
err             string[python]
dtype: object

In [95]:
dat2.dtypes

System          object
Type            object
RA(deg)         object
Dec(deg)        object
Vmag            object
Kmag            object
length          object
depth           object
T0(HJDorBJD)    object
T0err           object
Period(day)     object
Perioderr       object
Teff            object
err             object
err             object
[Fe/H]          object
erru            object
errd            object
M_A             object
errup           object
errdn           object
R_A             object
errup           object
errdn           object
loggA           object
errup           object
errdn           object
rho_A           object
errup           object
errdn           object
e               object
errup           object
errdown         object
a(AU)           object
errup           object
errdown         object
M_b             object
errup           object
errdn           object
R_b             object
errup           object
errdn           object
g_b             object
errup           object
errdn           object
rho_b           object
errup           object
errdn           object
Teq             object
err             object
err             object
Lambda          object
err             object
err             object
Psi             object
err             object
err             object
dtype: object